<header class="header">

    <section class="content menu-content">
        <div class="menu logo">

        </div>

        <div class="menu"><a href="#">Conheça a Click</a></div>
        <div class="menu"><a href="#">Como funciona</a></div>
        <div class="menu"><a href="#">Seja um parceiro</a></div>
        <div class="menu menu-last"><a href="#">faça seu login</a></div>
    </section>
</header>