<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta charset="UTF-8">
    <title>Click Consciente</title>

    <link rel="stylesheet" href="css/master.css">

</head>
<body>
<div class="container">
    <?php include("header.phtml"); ?>
    <div class="content main home-first">
        <div>
            <h1>Seja Consciente</h1>
            <p>Conforme o mundo gira, a Click evolui. Ao conectar condomínios e cooperativas diretamente através de nosso aplicativo.</p>
            <div class="menu menu-last btn-cadastro"><a href="#">Cadastre-se</a></div>
        </div>
        <div class="fone-hand">
            <img src="img/fone-hand.png" alt="telefone com info">
        </div>
    </div>

</div>

<div>

</div>

<div>

</div>
<?php include("footer.phtml"); ?>
</body>
</html>
